import re
import time
from io import StringIO

import pandas as pd
import requests
from bs4 import BeautifulSoup
from tabulate import tabulate

from bdc_analyzer import (
    get_headers,
    get_cik,
    get_shareholder_equity,
    fetch_latest_10k_url,
    fetch_filing_url_for_period,
    period_to_year,
    clean_num,
)


def _is_blank(v):
    s = '' if pd.isna(v) else str(v).strip()
    return s == '' or s.lower() in ('nan', 'none', '—', '-')


def _collapse_repeated_name(s: str) -> str:
    s = re.sub(r'\s+', ' ', str(s)).strip().upper()
    s = re.split(r'\s[—–-]\s', s)[0]
    words = s.split()
    if len(words) >= 6:
        n = len(words)
        for k in range(n // 3, n // 2 + 1):
            if words[:k] == words[k:2 * k]:
                return ' '.join(words[:k])
    return s


def _canon_key(name: str) -> str:
    s = _collapse_repeated_name(name)
    s = re.sub(r'\([^\)]*\)', ' ', s)
    s = re.sub(r'[^A-Z0-9 ]', ' ', s)
    toks = [t for t in s.split() if t not in {
        'LLC', 'INC', 'LTD', 'LP', 'L', 'P', 'CORP', 'CORPORATION', 'CO', 'AND', 'THE',
        'HOLDINGS', 'HOLDING', 'PARENT', 'TOPCO', 'MIDCO', 'BIDCO', 'BLOCKER', 'SERIES'
    }]
    return ' '.join(toks[:4])


def _clean_display_name(name: str) -> str:
    s = _collapse_repeated_name(name)
    # remove footnote markers like (3)(4)(9)
    s = re.sub(r'\(\d+\)', '', s)
    s = re.sub(r'\s+', ' ', s).strip(' ,;')
    return s


def _display_name_key(name: str) -> str:
    s = _clean_display_name(name).upper()
    s = re.sub(r'[^A-Z0-9 ]', ' ', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s


def _is_summary_like_name(name: str) -> bool:
    n = _clean_display_name(name).upper()
    if not n:
        return True
    patterns = [
        r'^TOTAL\b', r'^SUBTOTAL\b', r'^NET\b',
        r'\bDEBT INVESTMENTS\b', r'\bEQUITY INVESTMENTS\b',
        r'\bFIRST LIEN\b', r'\bSECOND LIEN\b',
        r'\bSENIOR SECURED\b', r'\bPREFERRED STOCK\b',
        r'\bLP INTEREST\b', r'\bREVOLVING LINE OF CREDIT\b',
        r'\bASSET BASED\b', r'\bALL ASSETS\b',
    ]
    for p in patterns:
        if re.search(p, n):
            return True
    if len(n.split()) <= 3 and any(k in n for k in ['DEBT', 'CREDIT', 'INVESTMENTS', 'STOCK', 'INTEREST', 'SECURED']):
        return True
    return False


def _enrich_business_intro(df: pd.DataFrame) -> pd.DataFrame:
    """Keep placeholder intro; final business description is generated by skill response layer."""
    out = df.copy()
    out['业务简介'] = '企业借款主体或特定项目控股公司。'
    return out
def _retry_get_content(url: str, retries: int = 6, sleep_s: int = 3):
    last = None
    for _ in range(retries):
        try:
            r = requests.get(url, headers=get_headers(), timeout=120)
            r.raise_for_status()
            return r.content
        except Exception as e:
            last = e
            time.sleep(sleep_s)
    raise RuntimeError(f'fetch failed after retries: {last}')


def _pick_num(vals, idx):
    if idx >= len(vals):
        return None
    v = clean_num(vals[idx])
    if pd.isna(v):
        return None
    return float(v)


def _detect_colmap(df: pd.DataFrame):
    """Detect key columns and candidate amount blocks for BXSL SoI tables."""
    if df.shape[1] < 20:
        return None

    tops = []
    for c in range(df.shape[1]):
        t0 = str(df.iloc[0, c]) if len(df) > 0 else ''
        t1 = str(df.iloc[1, c]) if len(df) > 1 else ''
        t2 = str(df.iloc[2, c]) if len(df) > 2 else ''
        txt = f"{t0} {t1} {t2}".lower()
        tops.append(txt)

    def find_cols(keyword):
        return [i for i, t in enumerate(tops) if keyword in t]

    company_cols = find_cols('company') + find_cols('investment') + find_cols('investments')
    invest_cols = find_cols('investment') + find_cols('investments')
    amort_cols = find_cols('amortized cost')
    # TSLX variants may label amount as Cost or Principal.
    cost_cols = [i for i, t in enumerate(tops) if (' cost' in t or t.strip().startswith('cost')) and 'amortized cost' not in t]
    principal_cols = find_cols('principal')
    fair_cols = find_cols('fair value') + find_cols('fairvalue')

    amount_cols = amort_cols if amort_cols else (cost_cols if cost_cols else principal_cols)

    if not company_cols or not amount_cols or not fair_cols:
        # TSLX continuation tables may lose header labels after pagination.
        # Fallback fixed layout seen in 27-column SoI fragments.
        if df.shape[1] >= 22:
            return {
                'company': 0,
                'invest': 2 if df.shape[1] > 2 else 0,
                'amort_cols': [16],
                'fair_cols': [21],
            }
        return None

    company_col = company_cols[0]
    invest_col = invest_cols[0] if invest_cols else max(0, company_col + 6)

    return {
        'company': company_col,
        'invest': invest_col,
        'amort_cols': sorted(set(amount_cols)),
        'fair_cols': sorted(set(fair_cols)),
    }


def _infer_table_context_year(tbl):
    """Infer whether a table belongs to 2025 or 2024 SoI section by nearby heading text."""
    year_dist = None
    year_val = None
    soi_dist = None

    for i, s in enumerate(tbl.find_all_previous(string=True, limit=400)):
        t = ' '.join(str(s).split())
        if not t:
            continue
        low = t.lower()

        if soi_dist is None and ('schedule of investments' in low):
            soi_dist = i

        if year_dist is None:
            m = re.search(r'(january|february|march|april|may|june|july|august|september|october|november|december)\s+\d{1,2},\s*(20\d{2})', low)
            if m:
                year_dist = i
                year_val = int(m.group(2))

        if soi_dist is not None and year_dist is not None:
            break

    if soi_dist is None or year_val is None:
        return None
    return year_val


def _parse_obdc_year(url: str, target_year: int) -> pd.DataFrame:
    soup = BeautifulSoup(_retry_get_content(url), 'lxml')

    all_rows = []
    carry_company = None  # handle page-break continuation tables with blank company cells

    tables = soup.find_all('table')

    # Build candidate list first, then fill year=None by nearest known-year table.
    candidates = []
    for idx, tbl in enumerate(tables):
        txt = tbl.get_text(' ', strip=True).lower()
        if 'company' not in txt and 'investments' not in txt and 'investment' not in txt and 'loan' not in txt:
            continue
        if ('amortized cost' not in txt and ' cost ' not in f' {txt} ' and 'principal' not in txt and ' par ' not in f' {txt} ' and 'loan' not in txt):
            continue
        if 'fair value' not in txt and 'fairvalue' not in txt and ' value ' not in f' {txt} ' and 'loan' not in txt:
            continue
        candidates.append((idx, tbl, txt, _infer_table_context_year(tbl)))

    # Fill missing years by nearest known-year neighbor within SoI run.
    known = [(i, y) for i, _, _, y in candidates if y is not None]
    resolved = []
    for i, tbl, txt, y in candidates:
        if y is not None:
            resolved.append((i, tbl, txt, y))
            continue
        if not known:
            continue
        nearest = min(known, key=lambda p: abs(p[0] - i))
        if abs(nearest[0] - i) <= 12:
            y = nearest[1]
            resolved.append((i, tbl, txt, y))

    for _, tbl, txt, ctx_year in resolved:
        if ctx_year != target_year:
            continue

        # TSLX layouts may omit explicit % of net assets in some split tables.
        try:
            df = pd.read_html(StringIO(str(tbl)))[0]
        except Exception:
            continue

        colmap = _detect_colmap(df)
        if not colmap:
            continue

        company_col = colmap['company']
        invest_col = colmap['invest']

        amort_cols = colmap['amort_cols']
        fair_cols = colmap['fair_cols']

        # map by paired order: left block tends older, right block tends current in OBDC 2025 filing
        pairs = list(zip(amort_cols[:len(fair_cols)], fair_cols[:len(amort_cols)]))
        if not pairs:
            continue
        resolved_years = [yy for _, _, _, yy in resolved if yy is not None]
        primary_year = max(resolved_years) if resolved_years else target_year
        if target_year == primary_year:
            amort_candidates = [p[0] for p in pairs[::-1]]
            fair_candidates = [p[1] for p in pairs[::-1]]
        else:
            amort_candidates = [p[0] for p in pairs]
            fair_candidates = [p[1] for p in pairs]

        detail = {}
        subtotal = {}

        current = carry_company
        closed = False

        for _, row in df.iterrows():
            vals = list(row.values)

            company_raw = str(vals[company_col]).strip() if company_col < len(vals) else ''
            inv_raw = str(vals[invest_col]).strip() if invest_col < len(vals) else ''

            comp_blank = _is_blank(company_raw)
            inv_blank = _is_blank(inv_raw)

            if not comp_blank:
                low = company_raw.lower()
                if any(k in low for k in ['company', 'schedule of investments', 'industry', 'total']):
                    continue
                if _is_summary_like_name(company_raw):
                    current = None
                    closed = False
                    continue
                current = _collapse_repeated_name(company_raw)
                closed = False

            if current is None:
                continue

            face = None
            fair = None
            for c in amort_candidates:
                face = _pick_num(vals, c)
                if face is not None:
                    break
            for c in fair_candidates:
                fair = _pick_num(vals, c)
                if fair is not None:
                    break
            if face is None and fair is None:
                continue

            f = 0.0 if face is None else face
            r = 0.0 if fair is None else fair

            if comp_blank and inv_blank:
                if not closed:
                    subtotal[current] = (f, r)
                    closed = True
                continue

            if closed:
                continue

            # detail rows should carry investment text
            if inv_blank:
                continue

            a, b = detail.get(current, (0.0, 0.0))
            detail[current] = (a + f, b + r)

        # Prefer explicit subtotal rows (blank company/investment line) when present,
        # because detail lines can be partial tranches while subtotal reflects the
        # intended company-level amount for that table block.
        chosen = {}
        for name, (f, r) in detail.items():
            chosen[name] = (f, r, 0)
        for name, (f, r) in subtotal.items():
            chosen[name] = (f, r, 1)

        for name, (f, r, is_subtotal) in chosen.items():
            if _is_summary_like_name(name):
                continue
            if f > 0:
                all_rows.append({'CanonKey': _canon_key(name), 'CompanyKey': name, 'Face': f, 'Fair': r, 'IsSubtotal': is_subtotal})

        # Preserve last seen company for continuation tables of the same year section.
        if current is not None:
            carry_company = current

    if not all_rows:
        return pd.DataFrame(columns=['CanonKey', 'CompanyKey', 'Face', 'Fair'])

    out = pd.DataFrame(all_rows)
    out = out[out['CanonKey'].str.len() > 0]
    # Dedupe repeated analytical tables for TSLX:
    # prioritize larger face first (more likely true instrument amount),
    # then lower fair as tie-breaker. Do not force subtotal priority because
    # continuation tables may surface section subtotal lines under current company.
    out = out.sort_values(['CanonKey', 'Face', 'Fair', 'IsSubtotal'], ascending=[True, False, True, False])
    out = out.groupby('CanonKey', as_index=False).first()[['CanonKey', 'CompanyKey', 'Face', 'Fair']]
    return out


def analyze(ticker, periodA=None, periodB=None):
    cik = get_cik(ticker)
    equity_usd = get_shareholder_equity(cik) or 1000000000

    # Single-file policy: use latest 10-K and extract both 2025 and 2024 from that filing.
    fallback_notes = []
    if periodA and periodB:
        year_a = period_to_year(periodA)
        year_b = period_to_year(periodB)
        url_a, resolved_a, fb_a = fetch_filing_url_for_period(cik, periodA, allow_fallback=True, return_meta=True)
        url_b, resolved_b, fb_b = fetch_filing_url_for_period(cik, periodB, allow_fallback=True, return_meta=True)
        if fb_a:
            fallback_notes.append(f"periodA 请求 {periodA} 不可用，已回退到最近可用期 {resolved_a}")
        if fb_b:
            fallback_notes.append(f"periodB 请求 {periodB} 不可用，已回退到最近可用期 {resolved_b}")
    else:
        url_a = fetch_latest_10k_url(cik)
        url_b = url_a
        m = re.search(r'(20\d{2})', url_a)
        year_a = int(m.group(1)) if m else 2025
        year_b = year_a - 1

    dispA = periodA if periodA else str(year_a)
    dispB = periodB if periodB else str(year_b)

    df_a = _parse_obdc_year(url_a, year_a).rename(columns={'Face': 'Face_A', 'Fair': 'Fair_A', 'CompanyKey': 'CompanyKey_A'})
    df_b = _parse_obdc_year(url_b, year_b).rename(columns={'Face': 'Face_B', 'Fair': 'Fair_B', 'CompanyKey': 'CompanyKey_B'})

    # First align by canonical key, then aggregate by cleaned display name
    # so multiple tranches (first/second lien/revolver) under same entity are merged.
    merged = pd.merge(df_a, df_b, on='CanonKey', how='inner')
    if len(merged) == 0:
        print('\n| 公司名 | periodA face value（金额百万美元，下同） | periodA fair value | periodA face/fair（用百分比表示） | periodB face | periodB fair | periodB face/fair（用百分比表示） | 期间face/fair变化 | 公司主要业务的一句话简介 |')
        print('|---|---:|---:|---:|---:|---:|---:|---:|---|')
        return

    merged = merged[(merged['Face_A'] > 0) & (merged['Face_B'] > 0)]
    merged['DisplayName'] = merged['CompanyKey_A'].apply(_clean_display_name)
    merged['DisplayKey'] = merged['DisplayName'].apply(_display_name_key)

    merged = merged.groupby('DisplayKey', as_index=False).agg({
        'DisplayName': 'first',
        'Face_A': 'sum',
        'Fair_A': 'sum',
        'Face_B': 'sum',
        'Fair_B': 'sum',
    })

    merged['CompanyKey'] = merged['DisplayName']

    # Auto-detect unit scale: some filings are already in $ millions, others in $ thousands.
    # Heuristic: if median face is large, treat as thousands and convert to millions.
    scale = 1000 if merged['Face_A'].median() > 2000 else 1
    merged['Face_A_M'] = merged['Face_A'] / scale
    merged['Fair_A_M'] = merged['Fair_A'] / scale
    merged['Face_B_M'] = merged['Face_B'] / scale
    merged['Fair_B_M'] = merged['Fair_B'] / scale

    threshold_m = (equity_usd / 1000000) * 0.002
    merged = merged[merged['Face_A_M'] > threshold_m]

    merged['ratio_A'] = merged['Fair_A_M'] / merged['Face_A_M']
    merged['ratio_B'] = merged['Fair_B_M'] / merged['Face_B_M']
    merged['ratio_drop'] = merged['ratio_B'] - merged['ratio_A']

    out = merged[(merged['ratio_drop'] > 0) & (merged['ratio_A'] <= 1.0)].sort_values('ratio_drop', ascending=False).head(20).copy()
    out = _enrich_business_intro(out)

    out['Face_A_fmt'] = out['Face_A_M'].map('{:.2f}'.format)
    out['Fair_A_fmt'] = out['Fair_A_M'].map('{:.2f}'.format)
    out['ratio_A_fmt'] = (out['ratio_A'] * 100).map('{:.2f}%'.format)
    out['Face_B_fmt'] = out['Face_B_M'].map('{:.2f}'.format)
    out['Fair_B_fmt'] = out['Fair_B_M'].map('{:.2f}'.format)
    out['ratio_B_fmt'] = (out['ratio_B'] * 100).map('{:.2f}%'.format)
    out['ratio_change_fmt'] = (-out['ratio_drop'] * 100).map('{:.2f}%'.format)

    show = out[[
        'CompanyKey', 'Face_A_fmt', 'Fair_A_fmt', 'ratio_A_fmt',
        'Face_B_fmt', 'Fair_B_fmt', 'ratio_B_fmt', 'ratio_change_fmt', '业务简介'
    ]]
    show.columns = [
        '公司名', f'{dispA} face value（金额百万美元，下同）', f'{dispA} fair value', f'{dispA} face/fair（用百分比表示）',
        f'{dispB} face', f'{dispB} fair', f'{dispB} face/fair（用百分比表示）', '期间face/fair变化', '公司主要业务的一句话简介'
    ]

    if fallback_notes:
        print('\n' + '；'.join(fallback_notes))
    print('\n' + tabulate(show, headers='keys', tablefmt='pipe', showindex=False))


if __name__ == '__main__':
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument('--ticker', required=True)
    args = p.parse_args()
    analyze(args.ticker)
